import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="nl">
        <body className={`${inter.className}`}>
            <main className="flex flex-col min-h-screen items-center justify-center p-24 bg-[#F3F5F9]">
                {children}
            </main>
        </body>
    </html>
  )
}
